### ISSUE TITLE
code style and quality workflow does not seem to run on the master branch

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-matlab#114]
See here.
https://github.com/bids-standard/bids-matlab/runs/1734150473

**Comment by Remi-Gau** [comment]
the tests run with this config:

```yaml
on:
  push:
    branches:
      - master
      - main
      - dev
  pull_request:
    branches: '*'
```

the linter does not with this config:

```
on:
  push:
    branches: [master, main, dev]
  pull_request:
    branches: [master, main]
```
